Rails4: TODO: 10-patches.rb: comment out ActionView::Helpers::InstanceTag
<pre>
undefined method `add_options' for class `ActionView::Helpers::InstanceTag'
/home/xxxx/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-4.0.2/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method'
/home/xxxx/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-4.0.2/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
/REDMINE/hg-workdir/MY-WORK/bb-rails4/config/initializers/10-patches.rb:106:in `<class:InstanceTag>'
/REDMINE/hg-workdir/MY-WORK/bb-rails4/config/initializers/10-patches.rb:97:in `<module:Helpers>'
/REDMINE/hg-workdir/MY-WORK/bb-rails4/config/initializers/10-patches.rb:96:in `<module:ActionView>'
/REDMINE/hg-workdir/MY-WORK/bb-rails4/config/initializers/10-patches.rb:95:in `<top (required)>'

</pre>

--HG--
branch : rails4.20140111-0
extra : source : 2c2542ab557571f9d7434754b756f52db4e54ecf